/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graficas;

import java.awt.BorderLayout;
import java.awt.Component;
import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.embed.swing.JFXPanel;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.PieChart.Data;
import javafx.scene.chart.XYChart;
import javafx.scene.chart.XYChart.Series;
import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;

/**
 *
 * @author luis
 */
public class ventana extends javax.swing.JFrame {
    JFXPanel fxPanel;

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        fxPanel = new JFXPanel();
        //addChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jButton1.setText("Crear chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //addChart();
        addBars();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);

            }
        });
    }
    
    private void addChart(){
        Platform.runLater(new Runnable() {
            @Override
            public void run() {

                Scene scene = new Scene(new Group());
                ObservableList<PieChart.Data> pieChartData =
                FXCollections.observableArrayList(
                new PieChart.Data("Productivo", 20),
                new PieChart.Data("No productivo", 25),
                new PieChart.Data("No clasificado", 55));
                final PieChart chart = new PieChart(pieChartData);
                chart.setTitle("Reporte de productividad");

                
                ObservableList<Data> d = chart.getData();
                for(int i=0;i<d.size();i++)
                    System.out.println(d.get(i));
                


                jPanel1.setLayout(new java.awt.BorderLayout());
                
                ((Group) scene.getRoot()).getChildren().add(chart);
                fxPanel.setScene(scene);
                fxPanel.setSize(600, 500);
                fxPanel.setLocation(0, 0);
                System.out.println("Ancho de fxpanel : "  + fxPanel.getWidth());
                jPanel1.add(fxPanel, BorderLayout.CENTER);

                //Charts hover
                final Label caption = new Label("");
                caption.setTextFill(Color.DARKORANGE);
                caption.setStyle("-fx-font: 24 arial;");

                for (final PieChart.Data data : chart.getData()) {
                    data.getNode().addEventHandler(MouseEvent.MOUSE_PRESSED,
                        new EventHandler<MouseEvent>() {
                            @Override public void handle(MouseEvent e) {
                                caption.setTranslateX(e.getSceneX());
                                caption.setTranslateY(e.getSceneY());
                                caption.setText(String.valueOf(data.getPieValue()) + "%");
                             }
                        });
                }                   
                                
                
            }
        });
        //jPanel1.add((Component)chart);    
    }
    
    public void addBars(){
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                   String austria = "Austria";
                   String brazil = "Brazil";
                   String france = "France";
                   String italy = "Italy";
                   String usa = "USA";                
                   final CategoryAxis xAxis = new CategoryAxis();
                   final NumberAxis yAxis = new NumberAxis();
                   final BarChart<String,Number> bc = 
                       new BarChart<String,Number>(xAxis,yAxis);
                   bc.setTitle("Country Summary");
                   xAxis.setLabel("Country");       
                   yAxis.setLabel("Value");

                   XYChart.Series series1 = new XYChart.Series();
                   series1.setName("2003");       
                   series1.getData().add(new XYChart.Data(austria, 2560.34));
                   series1.getData().add(new XYChart.Data(brazil, 2014.82));
                   series1.getData().add(new XYChart.Data(france, 1000));
                   series1.getData().add(new XYChart.Data(italy, 3540.15));
                   series1.getData().add(new XYChart.Data(usa, 1200));   

                   XYChart.Series series2 = new XYChart.Series();
                   series2.setName("2004");
                   series2.getData().add(new XYChart.Data(austria, 5740.85));
                   series2.getData().add(new XYChart.Data(brazil, 4194.19));
                   series2.getData().add(new XYChart.Data(france, 4526.37));
                   series2.getData().add(new XYChart.Data(italy, 1732.16));
                   series2.getData().add(new XYChart.Data(usa, 1484.27));

                   XYChart.Series series3 = new XYChart.Series();
                   series3.setName("2005");
                   series3.getData().add(new XYChart.Data(austria, 4500.65));
                   series3.getData().add(new XYChart.Data(brazil, 4483.76));
                   series3.getData().add(new XYChart.Data(france, 1872.18));
                   series3.getData().add(new XYChart.Data(italy, 1755.31));
                   series3.getData().add(new XYChart.Data(usa, 926.68));

                   Scene scene  = new Scene(bc,800,450);
                   //bc.getData().addAll(series1, series2, series3); 
                   bc.getData().add(series1);
                   bc.getData().add(series2);
                   bc.getData().add(series3);
                    fxPanel.setScene(scene);
                    fxPanel.setSize(600, 500);
                    fxPanel.setLocation(0, 0);
                    for (final Series<String, Number> series : bc.getData()) {
                    for (final XYChart.Data<String, Number> data : series.getData()) {
                        Tooltip tooltip = new Tooltip();
                        tooltip.setText(data.getYValue().toString());
                        Tooltip.install(data.getNode(), tooltip);
                    }
                }
                    System.out.println("Ancho de fxpanel : "  + fxPanel.getWidth());
                    jPanel1.add(fxPanel, BorderLayout.CENTER);
            }
        });
    }  
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
